export const getKeyboard = () => {
  const initialKeyboard = [
    {
      id: 1,
      key: 1,
      letter: "й",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 2,
      key: 1,
      letter: "ц",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 3,
      key: 1,
      letter: "у",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 4,
      key: 1,
      letter: "к",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 5,
      key: 1,
      letter: "е",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 6,
      key: 1,
      letter: "н",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 7,
      key: 1,
      letter: "г",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },

    {
      id: 8,
      key: 2,
      letter: "ш",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 9,
      key: 2,
      letter: "щ",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 10,
      key: 2,
      letter: "з",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 11,
      key: 2,
      letter: "х",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 12,
      key: 2,
      letter: "ъ",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },

    {
      id: 13,
      key: 3,
      letter: "ф",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 14,
      key: 3,
      letter: "ы",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 15,
      key: 3,
      letter: "в",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 16,
      key: 3,
      letter: "а",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 17,
      key: 3,
      letter: "п",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 18,
      key: 3,
      letter: "р",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 19,
      key: 3,
      letter: "о",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },

    {
      id: 20,
      key: 4,
      letter: "л",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 21,
      key: 4,
      letter: "д",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 22,
      key: 4,
      letter: "ж",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 23,
      key: 4,
      letter: "э",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 24,
      key: 4,
      letter: "я",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 25,
      key: 4,
      letter: "ч",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 26,
      key: 4,
      letter: "с",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },

    {
      id: 27,
      key: 5,
      letter: "м",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 28,
      key: 5,
      letter: "и",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 29,
      key: 5,
      letter: "т",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 30,
      key: 5,
      letter: "ь",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 31,
      key: 5,
      letter: "б",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 32,
      key: 5,
      letter: "ю",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
    {
      id: 33,
      key: 5,
      letter: "стереть",
      backgroundColor: "#343548",
      color: "white",
      disabled: false,
    },
  ];
  return initialKeyboard;
};
